name: 自动打包APK
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install p7zip-full -y
      - run: |
          # 自动把大写分卷文件名改成小写，统一格式
          for f in A6403A5B2.Z*; do mv "$f" "$(echo "$f" | tr '[:upper:]' '[:lower:]')"; done
          # 7z自动识别所有分卷并解压
          7z x a6403a5b2.zip
          # 解压内层的源码压缩包
          7z x 508c593abd5a4553bec2090a6403a5b2.zip
          # 清理压缩包文件
          rm -rf *.z* 508c593abd5a4553bec2090a6403a5b2.zip
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: 最终APK安装包
          path: app/build/outputs/apk/debug/app-debug.apk
