name: 自动打包APK
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install p7zip-full -y
      - run: |
          # 直接使用大写分卷的主文件解压，无需改名
          7z x A6403A5B2.Z01
          # 解压内层源码压缩包
          7z x 508c593abd5a4553bec2090a6403a5b2.zip
          # 清理所有分卷与压缩包
          rm -rf A6403A5B2.Z* a6403a5b2.zip 508c593abd5a4553bec2090a6403a5b2.zip
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: 最终APK安装包
          path: app/build/outputs/apk/debug/app-debug.apk
